spring:
  # main:
  #   allow-circular-references: true
  application:
    name: usuarios
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              # action: create
              action: none
              create-target: schema.sql
      hibernate:
        format_sql: true
  flyway:
    # enabled: true
    enabled: false
    locations: classpath:db/migration
    # baseline-on-migrate: true
    baseline-on-migrate: false
springdoc:
  swagger-ui:
    path: /index.html
    operationsSorter: method
